### ISSUE TITLE
On Photo Detail, Twitter sharing hangs the app (see attached screenshot)

### ISSUE THREAD

**Issue by jspkm** [anbion/lyyv#24]
@suzy 

![img_0677](https://cloud.githubusercontent.com/assets/824101/5871003/bd0b2d78-a28b-11e4-9db0-52cd87a15bf8.PNG)

**Comment by suzycantabile** [comment]
how long did you wait for it?

**Comment by jspkm** [comment]
About 30 sec. Then I quit the app, then tried with another photo. The screenshot is from the second attempt. 

By the way, I am assuming FB posting will not be working until we get app id.

**Comment by suzycantabile** [comment]
Does the twitter lag still happening?

Also, you are right on FB. I can add people as a tester and they can test out sharing photo on their timeline. If not, it won't work until our app is fully submitted to the appstore.

**Comment by jspkm** [comment]
Turns out that Twitter sharing was working after all. What happend was:

1. I have 2 Twitter accounts, @jspkm, and @lyyvhq
2. I am logged into Twitter as @lyyvhq
3. Last week when the Twitter sharing was first introduced and I shared, it posted to @lyyvhq (see screenshot below)
4. When I posted yesterday, it posted to @jspkm although I was logged into Twitter as @lyyvhq (see screenshot below)

## Screenshot of last week version of Lyyv Twitter sharing:
![img_0679](https://cloud.githubusercontent.com/assets/824101/5885422/5dd644dc-a321-11e4-9982-a5cb40e049f0.PNG)




## Screenshot of yesterday and today's version of Lyyv Twitter sharing:
![img_0678](https://cloud.githubusercontent.com/assets/824101/5885420/452fc3b8-a321-11e4-8f68-7d382dd8ec24.PNG)

**Comment by suzycantabile** [comment]
I see, I'm trying something new with twitter, so let's see if new integration will work better or not.. give me a moment :smile:

**Comment by jspkm** [comment]
BTW, this would be different, but still an issue. I would think we need to provide the user to explicitly link and unlink to a Twitter and FB account. Currently, the linking happens quite fast, without explicitly asking user to take any steps to link. And then the user has option to share/not share on FB or Twitter, but no option to unlink from currently linked FB/Twitter accounts.

**Comment by suzycantabile** [comment]
right, I will work on that as a next step. Also, twitter linking is being changed so people can choose the account of their desire if they have multiple twitter accounts set up

**Comment by jspkm** [comment]
Cool, thx!

**Comment by jspkm** [comment]
FB sharing works! @suzy
