### ISSUE TITLE
On Camera, the Cast selection overlay lingers on

### ISSUE THREAD

**Issue by jspkm** [anbion/lyyv#25]
@suzy 
![](![](http://i.imgur.com/0IdQDPp.jpg))

**Comment by suzycantabile** [comment]
can you be more specific about this?

**Comment by jspkm** [comment]
Sure - Below is the screenshot. Steps I got there:

1. Took a picture
2. Moved to Cast and uploaded the pic
3. Came back to Camera, and below is what shows

I moved around to Trending, Cast, etc, but it did not go away. If I restart the app it goes away.


![img_0686](https://cloud.githubusercontent.com/assets/824101/5982170/6bddd29e-a875-11e4-9433-bd314e955af4.PNG)

**Comment by suzycantabile** [comment]
mmk got this, and should be fixed by the next upload :-)
