### ISSUE TITLE
When I click on a notification "Joseph you have n casts near you", I am taken to Camera

### ISSUE THREAD

**Issue by jspkm** [anbion/lyyv#27]
It seems logical place to take the user to is in the Cast, where the user can start viewing the photos.

@suzy @haiqing @suriyanto

**Comment by suzycantabile** [comment]
So do you think it should go to trending, and then go inside a cast? If there are multiple casts near you, which one do we open? I didn't implement this part just yet because we briefly talked about this feature and wasn't sure what to do

**Comment by jspkm** [comment]
Yes, I think it should take the user directly inside a cast. So the user experience 

- Is: Tap notification -> Seeing list of photos in a Cast called, say, "Cast 1"
- Is NOT: Tap notification -> See list of Casts ("Cast 1, Cast 2") -> Tap on Cast 2 _> See list of photos in Cast 2

As for choosing which cast, my suggestion is to choose the one with most photos.

**Comment by suzycantabile** [comment]
got it, if you need any help let me know @suriyanto

**Comment by suriyanto** [comment]
For which cast, is there any objection if we use the same logic as what is used to determine the ordering of the casts list in the camera posting view? It is by #hearts, #users, #photos.

Also we are getting @oneworld and @random all the time. Should these be considered as casts near you? Currently @oneworld has most hearts and photos, so it will always show as the cast after notification is clicked.

**Comment by jspkm** [comment]
The implementation decisions make sense to me. Including still showing SF rather than SJ to use your example.
